### ISSUE TITLE
EMC values, and learnable/recoverable tags of items not saving

### ISSUE THREAD

**Issue by Gammix1** [pahimar/Equivalent-Exchange#1076]
Using the latest version I could find - EquivalentExchange3-1.7.10-0.3.0.547
Whenever the game has been restarted, or just the world save has been rejoined, any changes made by the following commands:
`/ee3 set-energy-value-current-item ...`
`/ee3 set-current-item-not-recoverable`
`/ee3 set-current-item-not-learnable`
seem to not save at all, which is a little bit frustrating.
Issues #856 and #900 are similar.
Thanks for any assistance in advance!

**Comment by pahimar** [comment]
Issues #856 and #900 are no longer relevant as the entire system was rewritten in the May 2016 sprint.

Relevant code:
- set-energy-value-current-item: https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/command/CommandSetEnergyValueCurrentItem.java#L42-L105
- set-current-item-not-recoverable: https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/command/CommandSetCurrentItemNotRecoverable.java#L33-L49
- set-current-item-not-learnable: https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/command/CommandSetEnergyValueCurrentItem.java#L42-L105

Testing by tfox83 (using these commands extensively) for the FTB Inventions released showed these commands working properly.

For the set-energy-value-current-item, if you are setting pre-calculation value assignments when you are finished you *must* run the /ee3 regenerate-energy-values command.

**Comment by Gammix1** [comment]
The commands do work properly for me, and I have made sure to run the /ee3 regenerate-energy-values command, but their effects are still temporary. Any clue as to why that may be happening or is that how they are meant to work? I only have very limited knowledge on coding so I don't know what to make of they snippets you linked.
Thanks for responding so quickly, by the way

**Comment by FMC312** [comment]
i also cannot save any energy values using commands. It Have to be done in the .json file in the minecraft instalation directory

**Comment by pahimar** [comment]
Closing due to age
