### ISSUE TITLE
Chalks not working in Multiplayer

### ISSUE THREAD

**Issue by gaoyichuan** [pahimar/Equivalent-Exchange#1085]
Hi, pahimar!
When I try to making a Transmutation Tablet with a Chalk, the chalk circle just doesn't appear. Also I tried in singleplayer and it worked normally.
Mod version: EE3 0.3.0.547 with forge

**Comment by pahimar** [comment]
I need more info than "doesn't work." Screenshots and video help a lot.

**Comment by gaoyichuan** [comment]
In single player, when I hold a chalk in my hand, the circle can appear as it should do:
![single player](http://7xs1yb.dl1.z0.glb.clouddn.com/2016-07-01_10.30.28.png)

But in my multiplayer server, which I built with Thermos and the same version of EE3, the chalk circle just didn't appear, which made it impossible to build a Transmutation Tablet:
![multi player](http://7xs1yb.dl1.z0.glb.clouddn.com/2016-07-01_10.29.53.png)

**Comment by pahimar** [comment]
Does it appear at all on other large flat services? Have you tried reducing the size of the chalk circle (Shift+the charge keybinding)?

**Comment by Muswetyl** [comment]
Hello there, I´m also having trouble - it´s only the Beta release 1.0.0 aviable on the server - not updatet yet by the probider :( 
The chalk works if you empower/depower it but the transmutation table doesn´t change - it only gots the chalk circle on it but doesn´t transform!
Sad but true!
Hope the provider will update it soon because in 1.0.1 it works!

**Comment by gaoyichuan** [comment]
@pahimar I have tried that all, but the circles didn't appear on flat services. Also I have tried the keybind and shift+the keybind, nothing happened.

**Comment by x3n0ph0b3** [comment]
Had a similar issue and what Pahimar was hinting at fixed it for me, but I had to shift+charge several times, not just once. If that doesn't help we'll just have to dig.

**Comment by captcookie** [comment]
I am having issues as well. I was trying to expand it to a larger circle with v and it disappeared. I tried replacing the blocks, new chalk, everything.

**Comment by captcookie** [comment]
https://github.com/pahimar/Equivalent-Exchange-3/wiki/Transmutation-Tablet this helped me

**Comment by pahimar** [comment]
Closing due to age
