### ISSUE TITLE
Cannot Calcinate and get Minium Dust

### ISSUE THREAD

**Issue by desagas** [pahimar/Equivalent-Exchange#1099]
Hi Pahimar,

I have tried blocks of emerald, blocks of diamond, and several other things. The last release on curse 0.3.0.547 is what I am using, and I still do not get any red dust. So, basically, I can not use EE3 at all. Can you offer a suggestion?

**Comment by pahimar** [comment]
What is the value of minium dust/diamonds/emeralds/etc in your world? The probability of you getting minium dust is dependent on the values of objects.

**Comment by MFive15** [comment]
Hello,

I am having the same problem. I am using 0.3.0.547, and all items simply turn to ash in the calcinater. Diamond exchange energy is 8192. Any ideas?

**Comment by MexRex** [comment]
Hey! 

I just wanted to say hi and show  you something  really interesting, here take a look <http://ignazio.drhart.org/e8rji/586>

Kind regards, SHoCKYCooKIE

**Comment by TheAdventAgain** [comment]
I am having the same issue. Just for the hell of it I let a stack of diamonds burn up and got 64 ash. The following are some values of items as shown in my game:

Minium Dust: "No Exchange Energy value"
Diamond: 8192
Emeralds: 8192
Coal: 32
Iron Ingot: 256

**Comment by pahimar** [comment]
Closing due to age
