### ISSUE TITLE
aludel not cooking

### ISSUE THREAD

**Issue by 21calder** [pahimar/Equivalent-Exchange#1102]
My EE3 aludel is not making ash infused stone when i have the exact recipe I need some help

**Comment by pahimar** [comment]
Without more information than "it's not working" it's really hard to help you. We need version of the mod, and exact steps to reproduce what you are seeing.

We also need to see log files so we can see what is going on there.

**Comment by nick3131** [comment]
+1 this, I'm on tekkit in Minecraft 1.6.4 and the aludel is not making anything. I have the ash stone and fuel in the correct place. Let me know what other info you need and I can see if I can get it.
