### ISSUE TITLE
Issue In Multiplayer server - Missing items or Non Working Tablet - FTB Inventions

### ISSUE THREAD

**Issue by EtherImperial** [pahimar/Equivalent-Exchange#1107]
Version: 1.7.10-0.3.0.547
Issue Newly created Transmutation Tablets and Alchenomoicons do not function:

Ok so here's what i ran into today, There is one working Tablet working currently on the server, the first one created.  Any new tablet does not show any items from working or new books that show items in the working tablet.  Tested with Tables in Claimed chunks of friends, unclaimed chunks and even 10 blocks next to my own working table.  The tables all create properly but do not show any items even from known working books.  There is another issue that might be related or separate but i can't tell.  We have one user on the server who recently changed her IG name.  Any books she creates shows her old name to her, but to other people who see the same books it could be either name.  All books examined were made at the same time.

**Comment by pahimar** [comment]
Closing due to age
