### ISSUE TITLE
Crafting conflicts with other mods

### ISSUE THREAD

**Issue by Eirriuvan** [pahimar/Equivalent-Exchange#1108]
I run EE3 and Ex-Nilho.
EE3 has a shapeless crafting recipe (clay + bone meal) to make chalk (working)
Ex-Nihlo has a shapeless recipe (bone meal + clay) to make porcelain.
Depending on the order the mods are loaded, one of the above recipes gets over-written.

Can the recipe for chalk be changed to 1 clay and 2 bone meal?
(This sounds like it would make a 'chalkier' chalk)
### Version of Equivalent Exchange 3

1.7.10 - 0.3.0.547

**Comment by MercuriusXeno** [comment]
Depending on how chalk plays, there's no telling what the recipe might end up being; but it is trivial to allow some sort of configurable chalk recipe, I think. And not a bad suggestion considering servers and packs may intend different balances, the use of the recipe would be a smart play.

**Comment by pahimar** [comment]
Closing due to age
