### ISSUE TITLE
Exchange-Values reset on Server

### ISSUE THREAD

**Issue by Sazra** [pahimar/Equivalent-Exchange#1111]
I use ee3 on a custom ftb infinity server with a few extra mods, the server is located on my own pc
### What should have happened

the files should have been read without problems
### What actually happened

energy-values.json resets or gets deleted on servers and reconfigure with other values and/or missing values
### What steps do we have to follow so we can reproduce the issue

no idea
### Version of Equivalent Exchange 3

EquivalentExchange3-1.7.10-0.3.0.547
### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)

log files mentioning not existing files

**Comment by pahimar** [comment]
I need to see the logs in order to help you with this @Sazra

**Comment by spannerman79** [comment]
Dupe #989

**Comment by pahimar** [comment]
Closing due to age
