### ISSUE TITLE
Transmutation Tablet server/client crash.

### ISSUE THREAD

**Issue by Avarice** [pahimar/Equivalent-Exchange#1120]
I was able to successfully create a Transmutation Tablet on my server, but my client was disconnected and the server crashed. In SSP I was not even able to complete the creation of the tablet. As soon as I right-clicked with chalk on ash infused stone, my client crashed. The log linked is SSP.

edit: Server did not technically crash, however it could not be stopped by command, nor pinged.

EE3 V: 0.30.547

Pastebin: http://pastebin.com/DC70sj0T

**Comment by pahimar** [comment]
Closing due to age
