### ISSUE TITLE
Server crashes on startup when using latest version of EE3

### ISSUE THREAD

**Issue by jcarrete5** [pahimar/Equivalent-Exchange#1121]
### What should have happened
The server should not have crashed.

### What actually happened
The server crashed.

### What steps do we have to follow so we can reproduce the issue
Attempt to run a forge 12.18.2.2151 minecraft server running with the compiled EE3 jar from commit 120ad367fc3dd5f2db495f8d1de2238aa31c294f.

### Version of Equivalent Exchange 3
EquivalentExchange3-1.10.2-0.4.0.0
(Using forge version 12.18.2.2151 for minecraft 1.10.2)

### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)
[fml-server-latest.log](http://pastebin.com/GDSZiyue)
[latest.log](http://pastebin.com/0t2TXS4V)
[crash-report](http://pastebin.com/A0PkwKHr)

Thank you for your time

**Comment by pahimar** [comment]
Closing due to age
